### ISSUE TITLE
[BUG] Last update broke Icon Folder [Other Plugin]

### ISSUE THREAD

**Issue by Mara-Li** [aidenlx/alx-folder-note#63] opened 2022-03-06 08:58 UTC
The last update makes the [Icon Folder](https://github.com/FlorianWoelki/obsidian-icon-folder) plugin not work anymore. Icons are no longer charged by the plugin, either for the folder note or for the other ones.

I have no error in the console.

**Comment by Cammagno** [comment] 2022-03-06 16:23
> The last update makes the [Icon Folder](https://github.com/FlorianWoelki/obsidian-icon-folder) plugin not work anymore. Icons are no longer charged by the plugin, either for the folder note or for the other ones.

Same for me, all Folder Icons gone :(
I can set them again, but after closing and reopening Obsidian, they are gone again, so it seems they are not loaded anymore.

**Comment by Mara-Li** [comment] 2022-03-06 21:54
Yeah, I revert the old version because icon folder is One of my main plugin ;(

**Comment by aidenlx** [comment] 2022-03-07 01:59
this is not an issue of alx-folder-note, it's caused by obsidian-icon-folder's method to register explorer view. I've [opened a PR about this](https://github.com/FlorianWoelki/obsidian-icon-folder/pull/43), hopefully it will be merged and published soon

**Closed by aidenlx** 2022-03-07 01:59 UTC
